-- 0001_initial — das heutige Portal-Schema, 1:1.
--
-- Abbild dessen, was `babu_web._db()` seit je bei jedem Aufruf anlegt: die
-- 18 Tabellen samt ihrer nachgerüsteten Spalten (die `ALTER TABLE … ADD
-- COLUMN`-Blöcke dort sind hier schon eingerechnet und stehen an derselben
-- Stelle, an der SQLite sie angehängt hat) und die sieben Indizes.
--
-- Geschrieben in Postgres-Dialekt; `db._fuer_sqlite()` übersetzt die
-- Handvoll abweichender Typen zurück, damit `tests/test_db_dialekt.py`
-- beide Schemata nebeneinanderlegen und vergleichen kann.
--
-- Zwei bewusste Entscheidungen:
--
--   * `GENERATED BY DEFAULT AS IDENTITY`, nicht `ALWAYS`. SQLites
--     `INTEGER PRIMARY KEY AUTOINCREMENT` erlaubt es, eine Nummer von Hand
--     mitzugeben; `ALWAYS` verbietet das. `BY DEFAULT` hält den Unterschied
--     bei null.
--   * `DOUBLE PRECISION`, nicht `REAL`. SQLites REAL ist 8 Byte, Postgres'
--     REAL nur 4 — bei Preisen und Stundenlöhnen wäre das ein stiller
--     Genauigkeitsverlust.
--
-- Wahrheitswerte stehen weiter als INTEGER 0/1 da, nicht als BOOLEAN. Der
-- Code schreibt überall `1 if … else 0` und liest `bool(z[7])`; ein echter
-- BOOLEAN wäre schöner und gehört in eine spätere Migration, nicht in die,
-- die nichts ändern soll.

CREATE TABLE IF NOT EXISTS lesestatus (
    un       TEXT NOT NULL,
    dokument TEXT NOT NULL,
    zeit     TEXT NOT NULL,
    PRIMARY KEY (un, dokument)
);

CREATE TABLE IF NOT EXISTS einstellungen (
    un         TEXT NOT NULL,
    schluessel TEXT NOT NULL,
    wert       TEXT NOT NULL,
    PRIMARY KEY (un, schluessel)
);

CREATE TABLE IF NOT EXISTS registrierungen (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zeit   TEXT NOT NULL,
    daten  TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'neu'
);

-- gehoert_zu: Mitarbeiterkonten zeigen auf den Salon, dem die Daten gehören.
-- box: Hat dieses Konto eine eigene Belegbox? Bestehende Zugänge sind von
-- Hand eingerichtet — sie behalten ihre (DEFAULT 1).
CREATE TABLE IF NOT EXISTS nutzer (
    email         TEXT PRIMARY KEY,
    name          TEXT,
    salon         TEXT,
    rolle         TEXT NOT NULL DEFAULT 'salon',
    pw            TEXT NOT NULL,
    aktiv         INTEGER NOT NULL DEFAULT 1,
    angelegt      TEXT,
    letzter_login TEXT,
    gehoert_zu    TEXT,
    box           INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS abschluss_status (
    un   TEXT PRIMARY KEY,
    jahr INTEGER,
    json TEXT NOT NULL,
    zeit TEXT NOT NULL
);

-- darf_belege/darf_kasse/zugang: Rechte, die die Inhaberin je Person vergibt.
CREATE TABLE IF NOT EXISTS team (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    un          TEXT NOT NULL,
    name        TEXT NOT NULL,
    email       TEXT,
    lohn_art    TEXT NOT NULL DEFAULT 'fest',
    betrag      DOUBLE PRECISION,
    stundenlohn DOUBLE PRECISION,
    stunden     DOUBLE PRECISION,
    seit        TEXT,
    aktiv       INTEGER NOT NULL DEFAULT 1,
    angelegt    TEXT,
    darf_belege INTEGER NOT NULL DEFAULT 0,
    darf_kasse  INTEGER NOT NULL DEFAULT 0,
    zugang      TEXT
);

-- Termine enthalten Kundennamen — personenbezogen, also löschbar und damit
-- NICHT in der Belegbox (dort bleibt jede Fassung für immer).
CREATE TABLE IF NOT EXISTS termin (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    un          TEXT NOT NULL,
    start       TEXT NOT NULL,
    minuten     INTEGER NOT NULL,
    wer         TEXT,
    kundin      TEXT,
    leistung    TEXT,
    notiz       TEXT,
    abgesagt    INTEGER NOT NULL DEFAULT 0,
    angelegt    TEXT,
    preis       DOUBLE PRECISION,
    ust_satz    INTEGER,
    abgerechnet TEXT,
    zahlart     TEXT,
    kundin_id   INTEGER,
    bestaetigt  INTEGER,
    quelle      TEXT,
    telefon     TEXT,
    zahlung_ref TEXT
);
CREATE INDEX IF NOT EXISTS termin_un_start ON termin (un, start);

-- Kundenkartei: Namen, Notizen, Farbformeln, Allergiehinweise. Personen-
-- bezogene und teils gesundheitsnahe Daten — sie gehören hierher, wo sich
-- löschen lässt (Art. 17 DSGVO), nicht in die Belegbox.
CREATE TABLE IF NOT EXISTS kundin (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    un       TEXT NOT NULL,
    name     TEXT NOT NULL,
    telefon  TEXT,
    email    TEXT,
    notiz    TEXT,
    allergie TEXT,
    angelegt TEXT,
    zuletzt  TEXT
);
CREATE INDEX IF NOT EXISTS kundin_un ON kundin (un, name);

CREATE TABLE IF NOT EXISTS behandlung (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    un       TEXT NOT NULL,
    kundin   INTEGER NOT NULL,
    datum    TEXT NOT NULL,
    leistung TEXT,
    formel   TEXT,
    notiz    TEXT,
    termin   INTEGER,
    angelegt TEXT
);
CREATE INDEX IF NOT EXISTS behandlung_kundin ON behandlung (un, kundin, datum);

-- Leistungskatalog: was der Salon anbietet, wie lange es dauert, was es
-- kostet. Stammdaten des Betriebs.
CREATE TABLE IF NOT EXISTS leistung (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    un       TEXT NOT NULL,
    name     TEXT NOT NULL,
    preis    DOUBLE PRECISION NOT NULL,
    minuten  INTEGER NOT NULL,
    ust_satz INTEGER NOT NULL DEFAULT 19,
    aktiv    INTEGER NOT NULL DEFAULT 1,
    angelegt TEXT
);

-- Personalakte. Personenbezogen bis auf die Knochen — Geburtsdatum,
-- Anschrift, Bankverbindung, Steuernummer. Gehört deshalb hierher und nicht
-- in die Belegbox: was hier steht, muss sich löschen lassen. Die gescannten
-- Dokumente gehen dagegen in die Box, sie sind aufbewahrungspflichtig.
CREATE TABLE IF NOT EXISTS mitarbeiter (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    un                  TEXT NOT NULL,
    vorname             TEXT,
    name                TEXT,
    geburtsdatum        TEXT,
    geburtsname         TEXT,
    geburtsort          TEXT,
    staatsangehoerigkeit TEXT,
    strasse             TEXT,
    plz                 TEXT,
    ort                 TEXT,
    telefon             TEXT,
    email               TEXT,
    steuer_idnr         TEXT,
    rentenvers_nr       TEXT,
    krankenkasse        TEXT,
    kinderlos           INTEGER,
    kinder_abschlaege   INTEGER,
    iban                TEXT,
    bic                 TEXT,
    titel_bis           TEXT,
    art                 TEXT,
    eintritt            TEXT,
    austritt            TEXT,
    befristet_bis       TEXT,
    taetigkeit          TEXT,
    stunden_woche       DOUBLE PRECISION,
    tage_woche          DOUBLE PRECISION,
    entgelt             INTEGER,
    urlaubstage         INTEGER,
    vertrag_pfad        TEXT,
    vertrag_fassung     TEXT,
    vertrag_angenommen  TEXT,
    belehrungen         TEXT,
    erledigt            TEXT,
    stand               TEXT NOT NULL DEFAULT 'eingeladen',
    einladung           TEXT,
    eingeladen_am       TEXT,
    angelegt            TEXT
);
CREATE INDEX IF NOT EXISTS mitarbeiter_einladung ON mitarbeiter (einladung);

-- WhatsApp: ein Gesprächsfaden je Telefonnummer, damit „2" als Antwort
-- weiß, worauf es sich bezieht. Auch das sind personenbezogene Daten.
CREATE TABLE IF NOT EXISTS wa_faden (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    un          TEXT NOT NULL,
    telefon     TEXT NOT NULL,
    name        TEXT,
    stand       TEXT NOT NULL DEFAULT 'neu',
    wunsch      TEXT,
    vorschlaege TEXT,
    termin      INTEGER,
    stumm       INTEGER NOT NULL DEFAULT 0,
    begonnen    TEXT,
    zuletzt     TEXT,
    UNIQUE (un, telefon)
);

CREATE TABLE IF NOT EXISTS wa_nachricht (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    un        TEXT NOT NULL,
    faden     INTEGER NOT NULL,
    richtung  TEXT NOT NULL,
    text      TEXT NOT NULL,
    wa_id     TEXT,
    zeit      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS wa_nachricht_faden ON wa_nachricht (faden, id);

CREATE TABLE IF NOT EXISTS gespraech (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    un       TEXT NOT NULL,
    titel    TEXT,
    begonnen TEXT NOT NULL,
    zuletzt  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS nachricht (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gespraech INTEGER NOT NULL,
    rolle     TEXT NOT NULL,
    text      TEXT NOT NULL,
    zeit      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS nachricht_gespraech ON nachricht (gespraech, id);

CREATE TABLE IF NOT EXISTS app_schluessel (
    hash     TEXT PRIMARY KEY,
    un       TEXT NOT NULL,
    geraet   TEXT,
    erstellt TEXT NOT NULL,
    zuletzt  TEXT
);

-- Anlagenverzeichnis (BABU-58). Warum hier und nicht in der Belegbox: der
-- Eintrag ist ABGELEITET und VERÄNDERLICH. Der Wert steht in ganzen CENT als
-- INTEGER, nicht als Fließkomma — ein Cent Differenz im Anlagenverzeichnis
-- ist ein Fehler in der Bilanz.
CREATE TABLE IF NOT EXISTS anlagegut (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    un            TEXT NOT NULL,
    bezeichnung   TEXT NOT NULL,
    angeschafft   TEXT NOT NULL,
    wert_cent     INTEGER NOT NULL,
    nutzungsdauer INTEGER,
    art           TEXT,
    beleg         TEXT,
    notiz         TEXT,
    abgang        TEXT,
    angelegt      TEXT
);
CREATE INDEX IF NOT EXISTS anlagegut_un ON anlagegut (un, angeschafft);

-- Eine angeforderte Auswertung, die noch niemandem gehört. Vom Schlüssel
-- steht nur der sha256 hier — wer die Datenbank liest, kommt damit nicht
-- hinein.
CREATE TABLE IF NOT EXISTS einladung (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mail            TEXT NOT NULL,
    schluessel_hash TEXT NOT NULL UNIQUE,
    erstellt        TEXT NOT NULL,
    frist           TEXT NOT NULL,
    verbraucht      TEXT,
    stand           TEXT NOT NULL,
    gelesen         TEXT NOT NULL DEFAULT '{}',
    bericht         TEXT NOT NULL DEFAULT '',
    anriss          TEXT NOT NULL DEFAULT '',
    ip              TEXT
);
CREATE INDEX IF NOT EXISTS einladung_mail ON einladung (mail, erstellt);

-- Die neunzehnte Tabelle, und die einzige, die nicht `_db()` anlegt:
-- `gitlab_meldungen._puffer_tabelle()` legt sie beim ersten Puffern an. Sie
-- steht hier trotzdem, damit ein frisches Postgres vollständig ist und nicht
-- erst dann, wenn GitLab zum ersten Mal weg war.
CREATE TABLE IF NOT EXISTS meldung_puffer (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    angelegt_am TEXT NOT NULL,
    nutzlast    TEXT NOT NULL
);
