-- 0002_kanzlei_mandant_audit — die Tabellen aus Plan 21, Phase 2 und §7.
--
-- Abbild dessen, was `mandanten.schema()` und `audit.schema()` (mit
-- `passwort_reset.schema()`) auf der SQLite-Seite aus `_sqlite_schema()`
-- heraus anlegen. Dieselbe Regel wie in 0001: Postgres-Dialekt hier,
-- `db._fuer_sqlite()` übersetzt zurück, `tests/test_db_dialekt.py` legt
-- beide Schemata nebeneinander und vergleicht Spalte für Spalte.
--
-- Fremdschlüssel zeigen auf `nutzer(email)` — deshalb erst nach 0001.

-- Audit-Log: jede Verwaltungs- und Export-Handlung, ohne Geheimnisse.
CREATE TABLE IF NOT EXISTS audit_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zeit       TEXT NOT NULL,
    akteur_un  TEXT NOT NULL,
    aktion     TEXT NOT NULL,
    ziel_un    TEXT,
    mandant_id TEXT,
    details    TEXT NOT NULL DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS audit_log_zeit ON audit_log (id DESC);

-- Passwort-Reset per Einmal-Link; vom Schlüssel steht nur der Hash hier.
CREATE TABLE IF NOT EXISTS passwort_reset (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash TEXT NOT NULL UNIQUE,
    un         TEXT NOT NULL,
    erstellt   TEXT NOT NULL,
    laeuft_ab  TEXT NOT NULL,
    eingeloest TEXT
);
CREATE INDEX IF NOT EXISTS passwort_reset_un ON passwort_reset (un, erstellt);

-- Kanzlei, Mandant, Mitgliedschaft (Plan 21, Abschnitt 1.2).
CREATE TABLE IF NOT EXISTS kanzlei (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL,
    inhaber_un TEXT NOT NULL REFERENCES nutzer(email),
    angelegt   TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS mandant (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kanzlei_id   BIGINT NOT NULL REFERENCES kanzlei(id),
    name         TEXT NOT NULL,
    besitzer_un  TEXT NOT NULL REFERENCES nutzer(email),
    box_ref      TEXT,
    kontenrahmen TEXT,
    berater_nr   TEXT,
    mandant_nr   TEXT,
    status       TEXT NOT NULL DEFAULT 'box_ausstehend'
                 CHECK (status IN ('box_ausstehend','aktiv','pausiert','beendet')),
    angelegt     TEXT NOT NULL,
    UNIQUE (kanzlei_id, besitzer_un)
);
CREATE INDEX IF NOT EXISTS mandant_kanzlei ON mandant (kanzlei_id, status);

CREATE TABLE IF NOT EXISTS kanzlei_mitglied (
    kanzlei_id BIGINT NOT NULL REFERENCES kanzlei(id),
    un         TEXT NOT NULL REFERENCES nutzer(email),
    rolle      TEXT NOT NULL DEFAULT 'sachbearbeiter'
               CHECK (rolle IN ('inhaber','sachbearbeiter')),
    angelegt   TEXT NOT NULL,
    PRIMARY KEY (kanzlei_id, un)
);
