-- 0011_ambassador_cockpit — Pipeline, Einladungen und Geld der Ambassadorin.
--
-- Abbild der Inline-Anweisungen in `babu_web._sqlite_schema()`. Dieselbe
-- Regel wie in 0001–0010: Postgres-Dialekt hier, `db._fuer_sqlite()` übersetzt
-- zurück, `tests/test_db_dialekt.py` legt beide Schemata nebeneinander.
--
-- ambassador_einladung   jeder erzeugte Link / jede Einladungsmail — wer noch
--                        nicht eingelöst hat, ist ein potenzieller Kunde
-- ambassador_buchung     eine Provision je anerkanntem Meilenstein (Datum!);
--                        `auszahlung_id` ist gesetzt, sobald sie ausgezahlt ist
-- ambassador_auszahlung  ein Auszahlungslauf (quartalsweise zum 15., ab 100 €)
-- ambassador_salon       dazu die Daten der Meilensteine
CREATE TABLE IF NOT EXISTS ambassador_einladung
    (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     code TEXT NOT NULL,
     salon TEXT,
     email TEXT,
     slug TEXT NOT NULL,
     erstellt TEXT NOT NULL,
     gesendet TEXT,
     eingeloest TEXT);
CREATE INDEX IF NOT EXISTS ambassador_einladung_code
    ON ambassador_einladung (code, eingeloest);
CREATE TABLE IF NOT EXISTS ambassador_buchung
    (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     code TEXT NOT NULL,
     email TEXT NOT NULL,
     salon TEXT,
     meilenstein TEXT NOT NULL,
     betrag INTEGER NOT NULL,
     datum TEXT NOT NULL,
     auszahlung_id INTEGER);
CREATE TABLE IF NOT EXISTS ambassador_auszahlung
    (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     code TEXT NOT NULL,
     betrag INTEGER NOT NULL,
     datum TEXT NOT NULL,
     stichtag TEXT NOT NULL,
     von TEXT NOT NULL);
ALTER TABLE ambassador_salon ADD COLUMN gezeichnet_am TEXT;
ALTER TABLE ambassador_salon ADD COLUMN gehalten_am TEXT;
