-- 0014_auszahlung — Auszahlung an Ambassadorinnen mit Gutschrift und Bankdatei (seit 03.10.2026).
--
-- Abbild der Inline-Anweisungen in `babu_web._sqlite_schema()`. Dieselbe
-- Regel wie in 0001–0013. Go-live-Plan Phase 3.
--
-- ambassador_profil      wohin das Geld geht und wie sie steuerlich steht —
--                        eigene Tabelle, damit sich die Angaben getrennt
--                        löschen lassen
-- auszahlungslauf        ein Quartalslauf: Bankdatei (pain.001), Stand
--                        erstellt → ueberwiesen (oder verworfen)
-- ambassador_auszahlung  je Ambassadorin und Lauf EINE Gutschrift: Nummer,
--                        Beträge in Cent, Schnappschuss und PDF (base64) —
--                        der nächtliche pg_dump sichert sie mit
CREATE TABLE IF NOT EXISTS ambassador_profil
    (code TEXT PRIMARY KEY REFERENCES ambassador(code),
     kontoinhaber TEXT,
     iban TEXT,
     bic TEXT,
     strasse TEXT,
     plz TEXT,
     ort TEXT,
     land TEXT NOT NULL DEFAULT 'DE',
     steuerstatus TEXT,
     steuernummer TEXT,
     ust_id TEXT,
     zustimmung_am TEXT,
     zustimmung_fassung TEXT,
     geaendert TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS auszahlungslauf
    (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     lauf TEXT NOT NULL,
     stichtag TEXT NOT NULL,
     status TEXT NOT NULL,
     anzahl INTEGER NOT NULL DEFAULT 0,
     summe_cent INTEGER NOT NULL DEFAULT 0,
     msg_id TEXT,
     xml TEXT,
     erstellt TEXT NOT NULL,
     von TEXT NOT NULL,
     ueberwiesen TEXT,
     ueberwiesen_von TEXT);
ALTER TABLE ambassador_auszahlung ADD COLUMN lauf_id INTEGER;
ALTER TABLE ambassador_auszahlung ADD COLUMN gutschrift_nr TEXT;
ALTER TABLE ambassador_auszahlung ADD COLUMN netto_cent INTEGER;
ALTER TABLE ambassador_auszahlung ADD COLUMN ust_cent INTEGER;
ALTER TABLE ambassador_auszahlung ADD COLUMN brutto_cent INTEGER;
ALTER TABLE ambassador_auszahlung ADD COLUMN beleg TEXT;
ALTER TABLE ambassador_auszahlung ADD COLUMN pdf TEXT;
ALTER TABLE ambassador_auszahlung ADD COLUMN status TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS ambassador_auszahlung_nr
    ON ambassador_auszahlung (gutschrift_nr);
