-- 0017_gedaechtnis — der Chat bekommt sein Gedächtnis zurück.
--
-- Abbild der Inline-Anweisungen aus `babu_web._sqlite_schema()`. Dieselbe
-- Regel wie in 0001–0005: Postgres-Dialekt hier, `db._fuer_sqlite()`
-- übersetzt zurück, `tests/test_db_dialekt.py` legt beide Schemata
-- nebeneinander und vergleicht Spalte für Spalte.
--
-- Zwei Dinge, zwei Sorten Gedächtnis:
--
-- 1. `gespraech.betrieb` — der Salon, in dessen Box das Gespräch lief.
--    `un` allein reichte nicht: arbeitet eine Kanzlei nacheinander in zwei
--    Mandantenboxen, gehören beide Fäden ihrem Konto, und ohne diese
--    Spalte setzte die Frage im Salon A das Gespräch aus Salon B fort.
--    Nachgerüstet als ALTER, weil `gespraech` seit 0001 steht und die
--    Zeilen darin (Fäden aus der Zeit vor BABU-25) erhalten bleiben.
--    NULL heißt „aus der Zeit, als es die Spalte nicht gab" — solche Fäden
--    werden gelesen, aber nie fortgesetzt.
--
-- 2. `merksatz` — was sie babu über sich erzählt hat und was in keinem
--    Beleg steht: „ich habe zwei Minijobberinnen", „montags ist zu",
--    „bitte kurze Antworten". Personenbezogen, veränderlich, löschbar —
--    also Datenbank und ausdrücklich NICHT Belegbox (dort bliebe jede
--    Fassung für immer stehen, und Art. 17 DSGVO liefe ins Leere).
--
--    `betrieb` statt `un` ist Absicht: der Satz beschreibt den Salon, nicht
--    das Konto, das ihn eingetippt hat. Ein Sachbearbeiter der Kanzlei, der
--    morgen den Mandanten übernimmt, soll ihn sehen; wer einen anderen
--    Mandanten betreut, nie. Ohne Fremdschlüssel, wie `audit_log.mandant_id`
--    — ein gelöschtes Konto soll die Sätze nicht mitreißen, sie werden
--    ausdrücklich gelöscht und nicht nebenbei.
--
--    `quelle` sagt, woher der Satz kam ("gesagt" = sie hat babu im Gespräch
--    darum gebeten, "eingetragen" = sie hat ihn selbst hingeschrieben).
--    Beides ist IHRE Angabe; was das Modell nur vermutet, kommt nie hierher.
ALTER TABLE gespraech ADD COLUMN betrieb TEXT;

CREATE TABLE IF NOT EXISTS merksatz (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    betrieb   TEXT NOT NULL,
    text      TEXT NOT NULL,
    gelernt   TEXT NOT NULL,
    quelle    TEXT,
    gespraech INTEGER
);
CREATE INDEX IF NOT EXISTS merksatz_betrieb ON merksatz (betrieb, id);
