"""Automatikkonten des SKR04 — welches Konto seine Steuer selbst rechnet.

Aus dem DATEV-Kontenrahmen SKR04 2026 (Art.-Nr. 11175) gelesen: jedes Konto,
das dort mit AV (Automatik Vorsteuer) oder AM (Automatik Umsatzsteuer)
gekennzeichnet ist, samt dem Steuersatz aus seiner Bezeichnung. Die Legende
des Kontenrahmens: „Bei mit AV oder AM-Funktion gekennzeichneten Konten kann
die Aufhebung der Automatik mit dem Schlüssel 4 durchgeführt werden.“ — die
Steuer kommt also vom Konto, nicht vom Buchungsschlüssel.

Zwei Nutzer:
  extf.py      schreibt auf diese Konten KEINEN Steuerschlüssel (der Import
               rechnet die Steuer aus dem Konto; ein Schlüssel obendrauf ist
               ein Widerspruch, den erst die Kanzlei sieht).
  historie.py  löst beim Einlesen fremder Stapel den Satz aus dem Konto auf,
               wenn die Zeile keinen Schlüssel trägt.

Satz None heißt: steuerfrei oder besonderer Sachverhalt (EU, Reverse Charge),
kein fester Prozentsatz in der Bezeichnung.

Erzeugt am 2026-09-02 mit einem Skript über das PDF; von Hand nichts geändert.
"""
from __future__ import annotations

# konto -> (Art, Satz in %, Bezeichnung)
AUTOMATIK: dict[str, tuple[str, float | int | None, str]] = {
    "1181": ("AV", 7, 'Geleistete Anzahlungen 7 % Vorsteuer'),
    "1182": ("AV", 5, 'Geleistete Anzahlungen, 5 % Vorsteuer'),
    "1184": ("AV", 16, 'Geleistete Anzahlungen, 16 % Vorsteuer'),
    "1186": ("AV", 19, 'Geleistete Anzahlungen 19 % Vorsteuer Erhaltene Anzahlungen'),
    "3260": ("AM", 7, 'Erhaltene, versteuerte Anzahlungen 7 % USt (Verbindlichkeite'),
    "3261": ("AM", 5, 'Erhaltene, versteuerte Anzahlungen 5 % USt (Verbindlichkeite'),
    "3264": ("AM", 0, 'Erhaltene, versteuerte Anzahlungen 0 % USt (Verbindlichkeite'),
    "3270": ("AM", 16, 'Erhaltene, versteuerte Anzahlungen 16 % USt (Verbindlichkeit'),
    "3272": ("AM", 19, 'Erhaltene, versteuerte Anzahlungen 19 % USt (Verbindlichkeit'),
    "4100": ("AM", None, 'Steuerfreie Umsätze § 4 Nr. 8 ff. UStG'),
    "4105": ("AM", None, 'Steuerfreie Umsätze nach § 4 Nr. 12 UStG (Vermietung und Ver'),
    "4110": ("AM", None, 'Sonstige steuerfreie Umsätze Inland'),
    "4120": ("AM", None, 'Steuerfreie Umsätze nach § 4 Nr. 1a UStG'),
    "4125": ("AM", None, 'Steuerfreie innergemeinschaftliche Lieferungen nach § 4 Nr.'),
    "4130": ("AM", None, 'Lieferungen des ersten Abnehmers bei innergemeinschaftlichen'),
    "4133": ("AM", 19, 'Umsatzerlöse nach § 25 UStG 19 % USt1)'),
    "4134": ("AM", 19, 'Umsatzerlöse nach § 25a UStG 19 % USt1)'),
    "4135": ("AM", None, 'Steuerfreie innergemeinschaftliche Lieferungen von Neufahrze'),
    "4136": ("AM", 19, 'Umsatzerlöse nach §§ 25 und 25a UStG 19 % USt11)'),
    "4139": ("AM", None, 'Umsatzerlöse aus Reiseleistungen § 25 Abs. 2 UStG, steuerfre'),
    "4140": ("AM", None, 'Steuerfreie Umsätze Offshore etc.'),
    "4150": ("AM", None, 'Sonstige steuerfreie Umsätze (z. B. § 4 Nr. 2 bis 7 UStG)'),
    "4160": ("AM", None, 'Steuerfreie Umsätze ohne Vorsteuerabzug zum Gesamtumsatz geh'),
    "4165": ("AM", None, 'Steuerfreie Umsätze ohne Vorsteuerabzug zum Gesamtumsatz geh'),
    "4184": ("AM", None, 'Steuerfreie Erlöse Kleinunternehmer nach § 19 Abs. 1 UStG Ar'),
    "4290": ("AM", 0, 'Erlöse 0 % USt'),
    "4300": ("AM", 7, 'Erlöse 7 % USt'),
    "4310": ("AM", 7, 'Erlöse aus im Inland steuerpflichtigen EU-Lieferungen 7 % US'),
    "4315": ("AM", 19, 'Erlöse aus im Inland steuerpflichtigen EU-Lieferungen 19 % U'),
    "4334": ("AM", 7, 'Erlöse 7 % USt'),
    "4335": ("AM", None, 'Erlöse aus Lieferungen von Mobilfunkgeräten, Tablet-Computer'),
    "4336": ("AM", None, 'Erlöse aus im anderen EU-Land steuerpflichtigen sonstigen Le'),
    "4337": ("AM", None, 'Erlöse aus Leistungen, für die der Leistungsempfänger die Um'),
    "4338": ("AM", None, 'Erlöse aus im Drittland steuerbaren Leistungen, im Inland ni'),
    "4339": ("AM", None, 'Erlöse aus im anderen EU-Land steuerbaren Leistungen, im Inl'),
    "4340": ("AM", 16, 'Erlöse 16 % USt'),
    "4400": ("AM", 19, 'Erlöse 19 % USt'),
    "4410": ("AM", 19, 'Erlöse 19 % USt'),
    "4449": ("AM", 19, 'Erlöse aus im Inland steuerpflichtigen elektronischen Dienst'),
    "4564": ("AM", None, 'Provisionsumsätze, steuerfrei § 4 Nr. 8 ff. UStG'),
    "4565": ("AM", None, 'Provisionsumsätze, steuerfrei § 4 Nr. 5 UStG'),
    "4569": ("AM", 19, 'Provisionsumsätze 19 % USt'),
    "4610": ("AM", 7, 'Entnahme durch den Unternehmer für Zwecke außerhalb des Unte'),
    "4616": ("AM", 7, 'Entnahme durch den Unternehmer für Zwecke außerhalb des Unte'),
    "4620": ("AM", 19, 'Entnahme durch den Unternehmer für Zwecke außerhalb des Unte'),
    "4630": ("AM", 7, 'Verwendung von Gegenständen für Zwecke außerhalb des Unterne'),
    "4636": ("AM", 7, 'Verwendung von Gegenständen für Zwecke außerhalb des Unterne'),
    "4640": ("AM", 19, 'Verwendung von Gegenständen für Zwecke außerhalb des Unterne'),
    "4645": ("AM", 19, 'Verwendung von Gegenständen für Zwecke außerhalb des Unterne'),
    "4646": ("AM", 19, 'Verwendung von Gegenständen für Zwecke außerhalb des Unterne'),
    "4650": ("AM", 7, 'Unentgeltliche Erbringung einer sonstigen Leistung 7 % USt'),
    "4656": ("AM", 7, 'Unentgeltliche Erbringung einer sonstigen Leistung 7 % USt'),
    "4660": ("AM", 19, 'Unentgeltliche Erbringung einer sonstigen Leistung 19 % USt'),
    "4670": ("AM", 7, 'Unentgeltliche Zuwendung von Waren 7 % USt'),
    "4676": ("AM", 7, 'Unentgeltliche Zuwendung von Waren 7 % USt'),
    "4680": ("AM", 19, 'Unentgeltliche Zuwendung von Waren 19 % USt'),
    "4686": ("AM", 19, 'Unentgeltliche Zuwendung von Gegenständen 19 % USt'),
    "4701": ("AM", None, 'Erlösschmälerungen für steuerfreie Umsätze nach § 4 Nr. 8 ff'),
    "4702": ("AM", None, 'Erlösschmälerungen für steuerfreie Umsätze nach § 4 Nr. 2 bi'),
    "4703": ("AM", None, 'Erlösschmälerungen für sonstige steuerfreie Umsätze ohne Vor'),
    "4704": ("AM", None, 'Erlösschmälerungen für sonstige steuerfreie Umsätze mit Vors'),
    "4705": ("AM", None, 'Erlösschmälerungen aus steuerfreien Umsätzen § 4 Nr. 1a UStG'),
    "4706": ("AM", None, 'Erlösschmälerungen für steuerfreie innergemeinschaftliche Dr'),
    "4707": ("AM", None, 'Erlösschmälerungen für steuerfreie Umsätze nach § 19 Abs. 1'),
    "4708": ("AM", 19, 'Erlösschmälerungen für Umsätze nach § 25 UStG 19 % USt1)'),
    "4709": ("AM", 19, 'Erlösschmälerungen für Umsätze nach § 25a UStG 19 % USt1)'),
    "4710": ("AM", 7, 'Erlösschmälerungen 7 % USt'),
    "4719": ("AM", 0, 'Erlösschmälerungen 0 % USt GuV- Posten2) Programmverbindung4'),
    "4720": ("AM", 19, 'Erlösschmälerungen 19 % USt'),
    "4724": ("AM", None, 'Erlösschmälerungen aus steuerfreien innergemeinschaftlichen'),
    "4725": ("AM", 7, 'Erlösschmälerungen aus im Inland steuerpflichtigen EU-Liefer'),
    "4726": ("AM", 19, 'Erlösschmälerungen aus im Inland steuerpflichtigen EU-Liefer'),
    "4730": ("AM", None, 'Gewährte Skonti'),
    "4734": ("AM", 0, 'Gewährte Skonti 0 % USt'),
    "4736": ("AM", 19, 'Gewährte Skonti 19 % USt'),
    "4738": ("AM", None, 'Gewährte Skonti aus Lieferungen von Mobilfunkgeräten etc., f'),
    "4742": ("AM", None, 'Gewährte Skonti aus Erlösen aus im anderen EU-Land steuerpfl'),
    "4745": ("AM", None, 'Gewährte Skonti aus im Inland steuerpflichtigen EU-Lieferung'),
    "4748": ("AM", 19, 'Gewährte Skonti aus im Inland steuerpflichtigen EU-Lieferung'),
    "4750": ("AM", 7, 'Gewährte Boni 7 % USt'),
    "4760": ("AM", 19, 'Gewährte Boni 19 % USt'),
    "4780": ("AM", 7, 'Gewährte Rabatte 7 % USt'),
    "4790": ("AM", 19, 'Gewährte Rabatte 19 % USt'),
    "4834": ("AM", 16, 'Sonstige Erträge betrieblich und regelmäßig 16 % USt'),
    "4836": ("AM", 19, 'Sonstige Erträge betrieblich und regelmäßig 19 % USt'),
    "4841": ("AM", None, 'Sonstige Erträge betrieblich und regelmäßig, steuerfrei § 4'),
    "4842": ("AM", None, 'Sonstige betriebliche Erträge, steuerfrei z. B. § 4 Nr. 2 bi'),
    "4844": ("AM", None, 'Erlöse aus Verkäufen Sachanlagevermögen steuerfrei § 4 Nr. 1'),
    "4845": ("AM", 19, 'Erlöse aus Verkäufen Sachanlagevermögen 19 % USt (bei Buchge'),
    "4848": ("AM", None, 'Erlöse aus Verkäufen Sachanlagevermögen steuerfrei § 4 Nr. 1'),
    "4861": ("AM", None, 'Erlöse aus Vermietung und Verpachtung, umsatzsteuerfrei § 4'),
    "4862": ("AM", 19, 'Erlöse aus Vermietung und Verpachtung 19 % USt'),
    "4865": ("AM", 19, 'Erlöse aus Verkäufen von Wirtschaftsgütern des Umlaufvermöge'),
    "4866": ("AM", None, 'Erlöse aus Verkäufen von Wirtschaftsgütern des Umlaufvermöge'),
    "4867": ("AM", None, 'Erlöse aus Verkäufen von Wirtschaftsgütern des Umlaufvermöge'),
    "4941": ("AM", 7, 'Sachbezüge 7 % USt (Waren)'),
    "4945": ("AM", 19, 'Sachbezüge 19 % USt (Waren)'),
    "4947": ("AM", 19, 'Verrechnete sonstige Sachbezüge aus Fahrzeug-Gestellung 19 %'),
    "4948": ("AM", 19, 'Verrechnete sonstige Sachbezüge 19 % USt'),
    "5110": ("AV", 7, 'Einkauf Roh-, Hilfsund Betriebsstoffe 7 % Vorsteuer'),
    "5130": ("AV", 19, 'Einkauf Roh-, Hilfsund Betriebsstoffe 19 % Vorsteuer'),
    "5160": ("AV", 7, 'Einkauf Roh-, Hilfsund Betriebsstoffe, innergemeinschaftlich'),
    "5162": ("AV", 19, 'Einkauf Roh-, Hilfsund Betriebsstoffe, innergemeinschaftlich'),
    "5166": ("AV", 7, 'Einkauf Roh-, Hilfsund Betriebsstoffe, innergemeinschaftlich'),
    "5167": ("AV", 19, 'Einkauf Roh-, Hilfsund Betriebsstoffe, innergemeinschaftlich'),
    "5170": ("AV", 5.5, 'Einkauf Roh-, Hilfsund Betriebsstoffe 5,5 % Vorsteuer'),
    "5171": ("AV", 7.8, 'Einkauf Roh-, Hilfsund Betriebsstoffe 7,8 % Vorsteuer8)'),
    "5175": ("AV", 7, 'Einkauf Roh-, Hilfsund Betriebsstoffe aus einem USt-Lager §'),
    "5176": ("AV", 19, 'Einkauf Roh-, Hilfsund Betriebsstoffe aus einem USt-Lager §'),
    "5189": ("AV", 19, 'Erwerb Roh-, Hilfsund Betriebsstoffe als letzter Abnehmer in'),
    "5191": ("AV", 7, 'Energiestoffe (Fertigung) 7 % Vorsteuer'),
    "5192": ("AV", 19, 'Energiestoffe (Fertigung) 19 % Vorsteuer'),
    "5300": ("AV", 7, 'Wareneingang 7 % Vorsteuer'),
    "5347": ("AV", 7, 'Wareneingang 7 % Vorsteuer'),
    "5400": ("AV", 19, 'Wareneingang 19 % Vorsteuer'),
    "5418": ("AV", 19, 'Wareneingang 19 % Vorsteuer'),
    "5420": ("AV", 7, 'Innergemeinschaftlicher Erwerb 7 % Vorsteuer und 7 % Umsatzs'),
    "5425": ("AV", 19, 'Innergemeinschaftlicher Erwerb 19 % Vorsteuer und 19 % Umsat'),
    "5430": ("AV", 7, 'Innergemeinschaftlicher Erwerb ohne Vorsteuer und 7 % Umsatz'),
    "5435": ("AV", 19, 'Innergemeinschaftlicher Erwerb ohne Vorsteuer und 19 % Umsat'),
    "5440": ("AV", 19, 'Innergemeinschaftlicher Erwerb von Neufahrzeugen von Liefera'),
    "5505": ("AV", 5.5, 'Wareneingang 5,5 % Vorsteuer'),
    "5540": ("AV", 7.8, 'Wareneingang zum Durchschnittssatz nach § 24 UStG 7,8 % Vors'),
    "5550": ("AV", None, 'Steuerfreier innergemeinschaftlicher Erwerb'),
    "5552": ("AV", None, 'Erwerb 1. Abnehmer innerhalb eines Dreiecksgeschäftes'),
    "5553": ("AV", 19, 'Erwerb Waren als letzter Abnehmer innerhalb Dreiecksgeschäft'),
    "5560": ("AV", 7, 'Waren aus einem Umsatzsteuerlager, § 13a UStG 7 % Vorsteuer'),
    "5565": ("AV", 19, 'Waren aus einem Umsatzsteuerlager, § 13a UStG 19 % Vorsteuer'),
    "5710": ("AV", 7, 'Nachlässe 7 % Vorsteuer'),
    "5714": ("AV", 7, 'Nachlässe aus Einkauf Roh-, Hilfsund Betriebsstoffe 7 % Vors'),
    "5715": ("AV", 19, 'Nachlässe aus Einkauf Roh-, Hilfsund Betriebsstoffe 19 % Vor'),
    "5717": ("AV", 7, 'Nachlässe aus Einkauf Roh-, Hilfsund Betriebsstoffe, innerge'),
    "5718": ("AV", 19, 'Nachlässe aus Einkauf Roh-, Hilfsund Betriebsstoffe, innerge'),
    "5720": ("AV", 19, 'Nachlässe 19 % Vorsteuer'),
    "5724": ("AV", 7, 'Nachlässe aus innergemeinschaftlichem Erwerb 7 % Vorsteuer u'),
    "5725": ("AV", 19, 'Nachlässe aus innergemeinschaftlichem Erwerb 19 % Vorsteuer'),
    "5730": ("AV", None, 'Erhaltene Skonti'),
    "5733": ("AV", None, 'Erhaltene Skonti aus Einkauf Roh-, Hilfsund Betriebsstoffe'),
    "5736": ("AV", 19, 'Erhaltene Skonti 19 % Vorsteuer'),
    "5738": ("AV", 19, 'Erhaltene Skonti aus Einkauf Roh-, Hilfsund Betriebsstoffe 1'),
    "5741": ("AV", 19, 'Erhaltene Skonti aus Einkauf Roh-, Hilfsund Betriebsstoffe a'),
    "5743": ("AV", 7, 'Erhaltene Skonti aus Einkauf Roh-, Hilfsund Betriebsstoffe a'),
    "5745": ("AV", None, 'Erhaltene Skonti aus steuerpflichtigem innergemeinschaftlich'),
    "5748": ("AV", 19, 'Erhaltene Skonti aus steuerpflichtigem innergemeinschaftlich'),
    "5750": ("AV", 7, 'Erhaltene Boni 7 % Vorsteuer'),
    "5754": ("AV", 7, 'Erhaltene Boni aus Einkauf Roh-, Hilfsund Betriebsstoffe 7 %'),
    "5755": ("AV", 19, 'Erhaltene Boni aus Einkauf Roh-, Hilfsund Betriebsstoffe 19'),
    "5760": ("AV", 19, 'Erhaltene Boni 19 % Vorsteuer'),
    "5780": ("AV", 7, 'Erhaltene Rabatte 7 % Vorsteuer'),
    "5784": ("AV", 7, 'Erhaltene Rabatte aus Einkauf Roh-, Hilfsund Betriebsstoffe'),
    "5785": ("AV", 19, 'Erhaltene Rabatte aus Einkauf Roh-, Hilfsund Betriebsstoffe'),
    "5787": ("AV", 9, 'Erhaltene Skonti aus Einkauf Roh-, Hilfsund Betriebsstoffe 9'),
    "5790": ("AV", 19, 'Erhaltene Rabatte 19 % Vorsteuer'),
    "5792": ("AV", 19, 'Erhaltene Skonti aus Erwerb Roh-, Hilfsund Betriebsstoffe al'),
    "5793": ("AV", 19, 'Erhaltene Skonti aus Erwerb Waren als letzter Abnehmer inner'),
    "5795": ("AV", 9, 'Erhaltene Skonti 9,0 % Vorsteuer11)'),
    "5798": ("AV", 5.5, 'Erhaltene Skonti aus Einkauf Roh-, Hilfsund Betriebsstoffe 5'),
    "5906": ("AV", 19, 'Fremdleistungen 19 % Vorsteuer'),
    "5908": ("AV", 7, 'Fremdleistungen 7 % Vorsteuer'),
    "5910": ("AV", 7, 'Bauleistungen eines im Inland ansässigen Unternehmers 7 % Vo'),
    "5913": ("AV", 7, 'Sonstige Leistungen eines im anderen EU-Land ansässigen Unte'),
    "5915": ("AV", 7, 'Leistungen eines im Ausland ansässigen Unternehmers 7 % Vors'),
    "5920": ("AV", 19, 'Bauleistungen eines im Inland ansässigen Unternehmers 19 % V'),
    "5923": ("AV", 19, 'Sonstige Leistungen eines im anderen EU-Land ansässigen Unte'),
    "5925": ("AV", 19, 'Leistungen eines im Ausland ansässigen Unternehmers 19 % Vor'),
    "5930": ("AV", 7, 'Bauleistungen eines im Inland ansässigen Unternehmers ohne V'),
    "5933": ("AV", 7, 'Sonstige Leistungen eines im anderen EU-Land ansässigen Unte'),
    "5935": ("AV", 7, 'Leistungen eines im Ausland ansässigen Unternehmers ohne Vor'),
    "5940": ("AV", 19, 'Bauleistungen eines im Inland ansässigen Unternehmers ohne V'),
    "5943": ("AV", 19, 'Sonstige Leistungen eines im anderen EU-Land ansässigen Unte'),
    "5945": ("AV", 19, 'Leistungen eines im Ausland ansässigen Unternehmers ohne Vor'),
    "5950": ("AV", None, 'Erhaltene Skonti aus Leistungen, für die als Leistungsempfän'),
    "5953": ("AV", None, 'Erhaltene Skonti aus Leistungen, für die als Leistungsempfän'),
    "6281": ("AM", 7, 'Forderungsverluste 7 % USt (soweit unüblich hoch)'),
    "6286": ("AM", 19, 'Forderungsverluste 19 % USt (soweit unüblich hoch)'),
    "6884": ("AM", None, 'Erlöse aus Verkäufen Sachanlagevermögen steuerfrei § 4 Nr. 1'),
    "6885": ("AM", 19, 'Erlöse aus Verkäufen Sachanlagevermögen 19 % USt (bei Buchve'),
    "6888": ("AM", None, 'Erlöse aus Verkäufen Sachanlagevermögen steuerfrei § 4 Nr. 1'),
    "6931": ("AM", 7, 'Forderungsverluste 7 % USt (übliche Höhe)'),
    "6932": ("AM", None, 'Forderungsverluste aus steuerfreien EU-Lieferungen (übliche'),
    "6933": ("AM", 7, 'Forderungsverluste aus im Inland steuerpflichtigen EU-Liefer'),
    "6936": ("AM", 19, 'Forderungsverluste 19 % USt (übliche Höhe)'),
    "6938": ("AM", 19, 'Forderungsverluste aus im Inland steuerpflichtigen EU-Liefer'),
}


def automatik(konto: str | None) -> tuple[str, float | int | None] | None:
    """(Art, Satz) eines Automatikkontos — None, wenn das Konto keins ist."""
    e = AUTOMATIK.get(str(konto or "").strip())
    return (e[0], e[1]) if e else None


def satz_vom_konto(konto: str | None) -> float | int | None:
    """Der Steuersatz, den das Konto selbst rechnet — oder None."""
    e = AUTOMATIK.get(str(konto or "").strip())
    return e[1] if e else None
